# Generated by Django 3.2.7 on 2021-10-08 21:16

import django.db.models.deletion
import fin_gen.apps.fingen_financeiro.models.moeda
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fingen_usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="moeda",
            field=models.ForeignKey(
                default=fin_gen.apps.fingen_financeiro.models.moeda.moeda_default,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="fingen_financeiro.moeda",
            ),
        ),
    ]
