# Generated by Django 3.2.7 on 2021-10-22 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fingen_usuario", "0002_usuario_moeda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        11, "Necessário no mínimo 11 caracteres"
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
    ]
