# Generated by Django 3.2.7 on 2021-10-18 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fingen_atividade", "0002_auto_20211014_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="data_da_atividade",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Data de vigência",
            ),
        ),
    ]
